---
- name: ensure prerequisites installed on webservers
  apt: name={{ item }} state=latest
  with_items:
    - python3.8-dev
    - build-essential
  tags: installation

- name: set python3 as default python
  command: sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1

- name: ensure pip is installed
  apt:
    name: python3-pip
    state: present
  tags: installation

- name: ensure pipenv is installed
  pip:
    name: pipenv
    state: latest
  tags: installation

- name: because django app has mysql these are essential
  apt: name={{ item }} state=present
  with_items:
    - libmysqlclient-dev
    - pkg-config
  tags: installation

- name: activate a virtual environment and install uwsgi
  command: pipenv install
  args:
    chdir: /home/vagrant/littlelemon/
  # pip:
    # name: uwsgi
    # # chdir: /home/vagrant/littlelemon/
    # virtualenv: /home/vagrant/littlelemon/
    # virtualenv_command: pipenv install && pipenv shell

  tags: installation

- template:
    src: "test.py"
    dest: "/home/vagrant/littlelemon"
  # tags: installation



