# - hosts: webservers
#   become: yes
#   roles:
#     - common
#     - apache2
#   tags:
#     web

# - hosts: proxy
#   become: yes
#   roles:
#     - common
#     - nginx
#   tags:
#     proxy

# - hosts: database
#   become: yes
#   roles:
#     - common
#     - mysql
#   tags: database

- hosts: webservers
  become: yes
  # vars:
    # http_port: 8000
    # https_port: 4443
    # html_welcome_msg: "Hello World!"
  # tasks:
  #   - include_tasks: tasks/apache2_install.yml

  # handlers:
  #   - include_tasks: handlers/main.yml
  roles:
    - common
    - apache2
  tags: web

- hosts: proxy
  become: yes
  roles:
    - common
    - nginx
  tags: proxy
