# - hosts: webservers
#   become: yes
#   roles:
#     - common
#     - apache2
#   tags:
#     web

# - hosts: proxy
#   become: yes
#   roles:
#     - common
#     - nginx
#   tags:
#     proxy

# - hosts: database
#   become: yes
#   roles:
#     - common
#     - mysql
#   tags: database

- hosts: webservers
  become: yes
  vars:
    http_port: 8000
    https_port: 4443
    html_welcome_msg: "Hello World!"
  tasks:

    - name: ensure apache is at the latest version
      apt:
        name: apache2
        state: latest

    - name: write the apache2 ports.conf config file 
      templates:
        src: templates/ports.conf.j2
        dest: /etc/apache2/ports.conf

    - name: write the apache2 index.html
      templates:
        src: templates/index.html.j2
        dest: /var/www/html/index.html