---
- name: Ensure git is installed
  apt:
    name: git
    state: present
  tags: installation

- name: clone the git repo
  git:
    repo: https://github.com/YasasRajitha/littlelemon.git
    dest: "/home/vagrant/littlelemon"
    update: no
    # force: yes
    # clone: no
    # diff_filter: "AM"
    version: master
