---
- name: ensure prerequisites installed on webservers
  apt: name={{ item }} state=latest
  with_items:
    - python3.8-dev
    - build-essential
  tags: installation

- name: set defaule settings
  command: sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1

- name: ensure pip is installed
  apt:
    name: python3-pip
    state: present
  tags: installation

- name: ensure pipenv is installed
  pip: name={{ item }} state=latest
  with_items:
    - asdf
    - pipenv
  tags: installation

- name: because django app has mysql these are essential
  apt: name={{ item }} state=present
  with_items:
    - libmysqlclient-dev
    - pkg-config
  tags: installation

- name: find pipenv location
  command: which pipenv
  register: pipenv_path

- name: find python3.8 location
  command: which python3.8
  register: py38_path

# - name: create virtual environment
#   command: pipenv install

# - name: activate virtual environment
#   command: "{{ pipenv_path.stdout }} --python {{ py3.8_path.stdout }} shell"

# - block:
- name: activate a virtual environment and install uwsgi
  pip:
    requirements: /home/vagrant/littlelemon/requirements.txt
    chdir: /home/vagrant/littlelemon/
    # executable: /usr/bin/python3.8
    virtualenv: /home/vagrant/littlelemon/
    # virtualenv_command: "uwsgi --httpjsvsgv :8001 --wsgi-file test.py"
    state: latest
  tags: installation

- name: "run uwsgi"
  shell: |
    source bin/activate
    uwsgi --http :8001 --wsgi-file test.py
  args:
    chdir: /home/vagrant/littlelemon/
    executable: /bin/bash

- template:
    src: "test.py"
    dest: "/home/vagrant/littlelemon"
  # tags: installation



